name: Update README activity
on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jamesgeorge007/github-activity-readme@master
        with:
          COMMIT_MSG: 'update activity log'
          MAX_LINES: 5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
